on:
  push:
    branches:
      - master
name: Build
jobs:
  test:
    name: Build
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: [
            'platform=iOS Simulator,OS=16.2,name=iPhone 14',
            'platform=tvOS Simulator,OS=16.1,name=Apple TV 4']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: |
          pod install
          set -o pipefail && \
          xcodebuild clean build \
          -workspace Hero.xcworkspace \
          -scheme Hero \
          -destination "${destination}" \
          -parallelizeTargets -showBuildTimingSummary \
          -enableCodeCoverage YES \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          | xcpretty
        env:
         destination: ${{ matrix.destination }}
